// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwnrymtaokajuqtgdaex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bnJ5bXRhb2thanVxdGdkYWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3OTY0MTksImV4cCI6MjA4NTM3MjQxOX0.lhtO3tQ4JWGAB72epPPCmTzdnmGfuBA5Jq87Vf-WIRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});