// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cznvtcvzotilcxajcflw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bnZ0Y3Z6b3RpbGN4YWpjZmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MTE4MDMsImV4cCI6MjA4NTE4NzgwM30.aI8P_LWwg7ak1fw6MIG51dBlF-yfq-xYf0i57WF4nHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});